
before_all do |lane|
    cocoapods
end

lane :my_lane do
    # Whatever actions you like go in here.
end

after_all do |lane|
    say("Successfully finished deployment (#{lane})!")
    slack(
        message: "Successfully submitted new App Update"
    )
    sh("./send_screenshots_to_team.sh") # Example
end

error do |lane, exception|
    slack(
      message: "Something went wrong with the deployment.",
      success: false,
      payload: { "Error Info" => exception.error_info.to_s } 
    )
end